### ISSUE TITLE
Síntesis de Calidad.

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IsaHuerta23#1]
[Síntesis de Calidad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IsaHuerta23/files/9619631/Sintesis.de.Calidad.pdf)

**Comment by bg55-a** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
